### ISSUE TITLE
ondemand dependencies

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#18]
@nickjer I am going through the SCL packages installed by Puppet compared to what's in ondemand.spec and these were installed by Puppet but not included in the spec.  Is it okay to remove these from Puppet?

```puppet
      $scl_packages = [
        'rh-ruby22-ruby-doc',
        'rh-ruby22-rubygems',
        'rh-ruby22-rubygems-devel',
        'rh-ruby22-rubygem-json',
        'rh-ruby22-rubygem-rdoc',
        'rh-ror41',
        'rh-ror41-rubygem-rack',
        'rh-ror41-rubygem-rails',
        'rh-ror41-rubygem-rails-doc',
        'rh-passenger40-ruby22',
      ]
```

**Comment by nickjer** [comment]
We might need to discuss that with @ericfranz. I believe quite a few of those packages were used so we didn't have to rely on Bundler. For example, I believe at one time we did `rails new ...` (relying on system-installed `rails` binary) as opposed to installing Rails through Bundler and running it.

But we may need the RubyGems package for continued development and releasing of gems. Maybe we need and `ondemand-dev` RPM for development of OnDemand?

**Comment by nickjer** [comment]
In short, I'd say that all the RPM requirements in `ondemand.spec` are necessary to build/run OnDemand. But the ones you listed above are more for development of OnDemand, which is why I'd lean towards an `ondemand-devel`.

But if we don't go that route, then I'd lean towards adding at least `rh-ruby22-rubygems` as a dependency in `ondemand.spec`. The Rails package is old and app developers have alternative ways of getting a `rails` bin as they can just run `gem install rails` and it will install a copy in their home directory.

**Comment by nickjer** [comment]
Hah, now I am leaning towards just adding `rh-rub22-rubygems` as a dependency into `ondemand.spec` to simplify things.

**Comment by ericfranz** [comment]
Whats the drawback of adding this as dependency to ondemand.spec right now?

        'rh-ruby22-rubygems',
        'rh-ruby22-rubygems-devel',
        'rh-ruby22-rubygem-json',
        'rh-ruby22-rubygem-rdoc',

In regards to rh-ror41:

We will likely want to include rh-ror50 in the future when upgrading to rh-ruby24 i.e. https://www.softwarecollections.org/en/scls/rhscl/rh-ror50/ i.e. rh-ruby24 and rh-nodejs6 and rh-ror50 are supported together. If rh-ror41 & rh-ror41-rubygem-rack are included right now, that still means the rack gem would only be available if running a command like:

scl enable rh-ruby22 rh-ror41 -- rackup

But without specifying rh-ror41 then Rack would not be available. If that is correct, which I think it is, then we currently by default do not start the PUN with the ror41 packaged enabled. So this could be excluded for now.

When we upgrade to rh-ror50 it would be nice to include this as a dependency so that basic Rack based apps (or even Sinatra based apps) could run without requiring a build step to install a copy of the Rack gem dependency. In our current OnDemand installation, the only app that can be deployed and run without a build step is a node.js app. Of course we might want to specify our own dependencies as rpms instead of using the rh-ror50 rpms.

The same goes with Python and wsgi.

**Comment by nickjer** [comment]
I don't believe there is a drawback to adding `rh-ruby22-rubygems` and `rh-ruby22-rubygems-devel` to `ondemand.spec`. As for the `json` and `rdoc` I am not sure if those are just dependencies of the above or were used for something else.

**Comment by treydock** [comment]
The only drawback of adding packages would be to `BuildRequires` as that would increase the build time since mock has to install all build dependencies for every build.

So to summarize, making sure I got everything:

* Remove all listed packages from Puppet
* Add rh-ruby22-rubygems and rh-ruby22-rubygems-devel to ondemand.spec as dependencies
* Leave rh-ror41, rh-passenger40-ruby22 and other packages listed as just orphaned, unmanaged packages on current web nodes.

**Comment by nickjer** [comment]
Sounds good to me.

**Comment by treydock** [comment]
Closing this, `1.3.0-2` of the RPM contains the updated dependencies.  When we bump to 1.3.0 we will want to be sure to put the release number back to 1.
