### ISSUE TITLE
compute node modules

### ISSUE THREAD

**Issue by johrstrom** [OSC/ondemand-packaging#213]
I have no idea how to package, much less distribute modules.  But it seems like we know how to `make` these packages pretty well. Maybe we could provide some rake tasks to do so.

`PREFIX=/my/websockify/dir rake package:module['websockify']` (or maybe install instead of package?).

I'm aware that the RPM may actually be easier - but it may allow folks to build things _to their node_ like python2 and 3 being requested in #212.

Not a priority and indeed - just a thought. It could very well be too much work with not enough payback. Totally happy to close as a `won't do` or keep open as a `maybe someday`.

**Comment by treydock** [comment]
I'm not sure this is really realistic because of just how much Lmod environments can vary.  There are already tools to handle this for HPC like Spank and Easybuild.  Rather than inventing our own way to install something into Lmod of TCL modules, just rely on those tools and if they don't provide tooling to install websockify, maybe we can add it and point people at those well established tools.

Also Rake tasks on HPC might not be realistic either.  Ruby is not a common software stack to install on HPC and can't assume OnDemand node can even write to modules (ie OSC doesn't even mount them on web nodes).  Typically the NFS or shared filesystem for Lmod modules is specific to a given cluster so not really something most would mount on shared web nodes.

**Comment by johrstrom** [comment]
Yea fine by me to close as won't/can't do.
