### ISSUE TITLE
Move %posttrans to %post

### ISSUE THREAD

**Issue by treydock** [OSC/ondemand-packaging#23]
@nickjer What was the rational for using `%posttrans` instead of having the logic in `%post`?  As far as I can tell they behave the same.

https://fedoraproject.org/wiki/Packaging:Scriptlets

The benefit to `%post` is `$1` will vary based on upgrade vs install.

**Comment by nickjer** [comment]
`%posttrans` occurs after `%preun` and `%postun` during an upgrade. Currently we don't modify Apache configuration in either of those hooks during an upgrade, so it may not be necessary to restart Apache in `%posttrans`.

I believe I carried it over from here:

https://git.centos.org/blob/rpms!httpd24-httpd/f5da3f64730f0abb0da4b77f17777ed5ab2138b1/SPECS!httpd.spec;jsessionid=b753kpy0nq331bunl6plpsfwc#L715

Do you ever see us modifying the Apache configuration during an upgrade process in particular as the old RPM is being removed? Otherwise I don't think it will be problematic to move it to `%post`.
